require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/finders", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Finder. As you add validations to Finder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Finder.create! valid_attributes
      get finders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      finder = Finder.create! valid_attributes
      get finder_url(finder)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_finder_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      finder = Finder.create! valid_attributes
      get edit_finder_url(finder)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Finder" do
        expect {
          post finders_url, params: { finder: valid_attributes }
        }.to change(Finder, :count).by(1)
      end

      it "redirects to the created finder" do
        post finders_url, params: { finder: valid_attributes }
        expect(response).to redirect_to(finder_url(Finder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Finder" do
        expect {
          post finders_url, params: { finder: invalid_attributes }
        }.to change(Finder, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post finders_url, params: { finder: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested finder" do
        finder = Finder.create! valid_attributes
        patch finder_url(finder), params: { finder: new_attributes }
        finder.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the finder" do
        finder = Finder.create! valid_attributes
        patch finder_url(finder), params: { finder: new_attributes }
        finder.reload
        expect(response).to redirect_to(finder_url(finder))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        finder = Finder.create! valid_attributes
        patch finder_url(finder), params: { finder: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested finder" do
      finder = Finder.create! valid_attributes
      expect {
        delete finder_url(finder)
      }.to change(Finder, :count).by(-1)
    end

    it "redirects to the finders list" do
      finder = Finder.create! valid_attributes
      delete finder_url(finder)
      expect(response).to redirect_to(finders_url)
    end
  end
end
